import { describe, expect, test } from "bun:test";
import { buildReviewComment } from "../post-review.formatter";
import type { PRReviewStateType } from "../../review.state";
import type { ReviewSummary } from "../../../agent/review-summary";

const state = {
  prTitle: "fix: update review LLM provider",
  changedFiles: ["apps/server/src/llm/llm.provider.ts"],
} as PRReviewStateType;

const summary: ReviewSummary = {
  overview: "This PR updates the review model and queue integration.",
  bullets: ["Uses GPT-OSS for Groq reviews.", "Adds Gemini as a fallback."],
  mergeAssessment: "The PR is not yet safe to merge.",
  mergeReason: "A blocking provider configuration issue requires attention.",
};

describe("buildReviewComment", () => {
  test("renders a clean review with the OpenMerge summary layout", () => {
    const output = buildReviewComment(state, [], 76_000, summary);

    expect(output).toContain("## OpenMerge Summary - fix: update review LLM provider");
    expect(output).toContain("This PR updates the review model and queue integration.");
    expect(output).toContain("- Uses GPT-OSS for Groq reviews.");
    expect(output).toContain("✅ **Looks good to merge!**");
    expect(output).toContain("No actionable issues found in 1 changed file.");
    expect(output).toContain("*Reviewed 1 file in 76.0s*");
    expect(output).not.toContain("Generated by");
    expect(output).not.toContain("—");
    expect(output).not.toContain("–");
    expect(output).not.toContain("<details>");
  });

  test("renders findings with merge assessment and files needing attention", () => {
    const output = buildReviewComment(
      state,
      [{
        filePath: "apps/server/src/llm/llm.provider.ts",
        line: 12,
        body: "Provider configuration fails in production.",
        severity: "HIGH",
        category: "BUG",
        blocking: true,
      }],
      48_300,
      summary,
    );

    expect(output).toContain("The PR is not yet safe to merge because 1 blocking issue requires attention.");
    expect(output).toContain("**Files Needing Attention:** `apps/server/src/llm/llm.provider.ts`");
    expect(output).toContain("Reviewed **1 file** · **1 issue** · **1 blocking**");
    expect(output).toContain("⛔ **Changes requested**");
  });

  test("requests changes for a blocking medium-severity finding", () => {
    const output = buildReviewComment(state, [{
      filePath: "apps/server/src/llm/llm.provider.ts",
      line: 12,
      body: "This issue blocks the review from being merged.",
      severity: "MEDIUM",
      category: "BUG",
      blocking: true,
    }], 1_000);

    expect(output).toContain("⛔ **Changes requested**");
    expect(output).toContain("1 blocking issue requires attention");
  });

  test("keeps a non-blocking high-severity finding as a suggestion", () => {
    const output = buildReviewComment(state, [{
      filePath: "apps/server/src/llm/llm.provider.ts",
      line: 12,
      body: "This issue is worth reviewing but does not block the merge.",
      severity: "HIGH",
      category: "BUG",
      blocking: false,
    }], 1_000);

    expect(output).toContain("⚠️ **Review complete**. Non-blocking suggestions noted.");
    expect(output).not.toContain("⛔ **Changes requested**");
    expect(output).toContain("The PR has no blocking issues; the remaining suggestions are non-blocking.");
  });

  test("uses non-blocking fallback guidance when all findings are non-blocking", () => {
    const output = buildReviewComment(state, [{
      filePath: "apps/server/src/llm/llm.provider.ts",
      line: 12,
      body: "This is a minor improvement suggestion.",
      severity: "LOW",
      category: "STYLE",
      blocking: false,
    }, {
      filePath: "apps/server/src/llm/gemini.config.ts",
      line: 8,
      body: "This could be documented more clearly.",
      severity: "MEDIUM",
      category: "DOCUMENTATION",
      blocking: false,
    }], 1_000);

    expect(output).toContain("This PR includes review suggestions that do not block merging.");
    expect(output).toContain("The PR has no blocking issues; the remaining suggestions are non-blocking.");
    expect(output).toContain("The remaining findings are non-blocking suggestions.");
    expect(output).not.toContain("The PR is not yet safe to merge");
  });

  test("escapes untrusted Markdown in the title, summary, and findings", () => {
    const output = buildReviewComment(
      {
        ...state,
        prTitle: "[Approve this](https://evil.example)\n## fake heading",
      },
      [{
        filePath: "apps/server/src/[unsafe].ts",
        line: 12,
        body: "[Ignore this](https://evil.example)\n# fake heading",
        severity: "HIGH",
        category: "SECURITY",
        blocking: true,
      }],
      1_000,
      {
        overview: "Review [this link](https://evil.example) and **ignore** the findings.",
        bullets: ["# injected heading", "Use `unsafe` input."],
        mergeAssessment: "The PR is not yet safe to merge.",
        mergeReason: "See [this link](https://evil.example) for details.",
      },
    );

    expect(output).toContain("\\[Approve this\\]\\(https\\://evil.example\\) \\#\\# fake heading");
    expect(output).toContain("Review \\[this link\\]\\(https\\://evil.example\\) and \\*\\*ignore\\*\\* the findings.");
    expect(output).toContain("\\# injected heading");
    expect(output).toContain("- `apps/server/src/[unsafe].ts:12` · **blocking** - \\[Ignore this\\]\\(https\\://evil.example\\) \\# fake heading.");
    expect(output).toContain("See \\[this link\\]\\(https\\://evil.example\\) for details.");
    expect(output).not.toContain("[Approve this](https://evil.example)");
    expect(output).not.toContain("https://evil.example");
    expect(output).not.toContain("\n## fake heading");
    expect(output).not.toContain("\n# fake heading");
  });
});
