import { describe, expect, test } from "bun:test";
import { buildReviewComment } from "../post-review.formatter";
import type { PRReviewStateType } from "../../review.state";
import type { ReviewSummary } from "../../../agent/review-summary";

const state = {
  prTitle: "fix: update review LLM provider",
  changedFiles: ["apps/server/src/llm/llm.provider.ts"],
} as PRReviewStateType;

const summary: ReviewSummary = {
  overview: "This PR updates the review model and queue integration.",
  bullets: ["Uses GPT-OSS for Groq reviews.", "Adds Gemini as a fallback."],
  mergeAssessment: "The PR is not yet safe to merge.",
  mergeReason: "A blocking provider configuration issue requires attention.",
};

describe("buildReviewComment", () => {
  test("renders a clean review with the OpenMerge summary layout", () => {
    const output = buildReviewComment(state, [], 76_000, summary);

    expect(output).toContain("## OpenMerge Summary - fix: update review LLM provider");
    expect(output).toContain("This PR updates the review model and queue integration.");
    expect(output).toContain("- Uses GPT-OSS for Groq reviews.");
    expect(output).toContain("✅ **Looks good to merge!**");
    expect(output).toContain("No actionable issues found in 1 changed file.");
    expect(output).toContain("*Reviewed 1 file in 76.0s*");
    expect(output).not.toContain("Generated by");
    expect(output).not.toContain("—");
    expect(output).not.toContain("–");
    expect(output).not.toContain("<details>");
  });

  test("renders findings with merge assessment and files needing attention", () => {
    const output = buildReviewComment(
      state,
      [{
        filePath: "apps/server/src/llm/llm.provider.ts",
        line: 12,
        body: "Provider configuration fails in production.",
        severity: "HIGH",
        category: "BUG",
        blocking: true,
      }],
      48_300,
      summary,
    );

    expect(output).toContain("The PR is not yet safe to merge because 1 blocking issue requires attention.");
    expect(output).toContain("**Files Needing Attention:** `apps/server/src/llm/llm.provider.ts`");
    expect(output).toContain("Reviewed **1 file** · **1 issue** · **1 blocking**");
    expect(output).toContain("⛔ **Changes requested**");
  });
});
